// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdantajapxeeahkxeib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZGFudGFqYXB4ZWVhaGt4ZWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzc1MzIsImV4cCI6MjA3MjcxMzUzMn0.fBaNYVNCcBgsQISkj1jS1uBCFHntIBtFlqHC2mtIBZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});